from __future__ import annotations

import json
from typing import Any, TypedDict

from app.llm.client import AnthropicLLMClient
from app.services.imagery import ImageryFragment
from app.shared.tracing import get_tracer

_VALID_CONFIDENCE_LEVELS = {"high", "moderate", "low"}


class MotifCandidate(TypedDict):
    label: str
    rationale: str
    confidence: str
    imagery_indices: list[int]


class MotifInductionError(RuntimeError):
    """Raised when motif induction cannot produce a valid response."""


class MotifInductor:
    """Induce abstract motif labels from extracted imagery fragments.

    Labels are open-vocabulary strings generated by the model.
    No predefined category list is used or consulted.
    """

    def __init__(self, llm_client: Any | None = None, *, max_retries: int = 1) -> None:
        self._client = llm_client or AnthropicLLMClient(model="claude-sonnet-4-6")
        self._max_retries = max_retries

    async def induce(self, fragments: list[ImageryFragment]) -> list[MotifCandidate]:
        tracer = get_tracer(__name__)
        system_prompt = self._build_system_prompt()
        user_prompt = self._build_user_prompt(fragments)
        last_error: Exception | None = None

        with tracer.start_as_current_span("motif_inductor.induce"):
            for _attempt in range(self._max_retries + 1):
                try:
                    raw_response = await self._client.complete(system_prompt, user_prompt)
                    return self._parse_candidates(raw_response, len(fragments))
                except (MotifInductionError, ValueError, json.JSONDecodeError) as exc:
                    last_error = exc

        raise MotifInductionError(
            "Motif induction failed after retry"
        ) from last_error

    def _build_system_prompt(self) -> str:
        return (
            "You induce abstract motif labels from concrete imagery fragments "
            "extracted from a dream journal entry.\n"
            "Return JSON only using the schema "
            '{"motifs":[{"label":"...","rationale":"...","confidence":"high|moderate|low",'
            '"imagery_indices":[0,1]}]}.\n'
            "Generate abstract motif labels from the imagery. "
            "Do not use predefined psychological categories. "
            "Do not interpret the dream. "
            "Name only the structural or thematic pattern visible in the imagery.\n"
            "imagery_indices is a list of zero-based indices into the provided "
            "imagery fragment list that support each motif.\n"
            "confidence must be one of: high, moderate, low.\n"
            "Return only the JSON object. No commentary."
        )

    def _build_user_prompt(self, fragments: list[ImageryFragment]) -> str:
        indexed_lines = "\n".join(
            f"{i}: {fragment['text']}" for i, fragment in enumerate(fragments)
        )
        return (
            "Induce abstract motif labels from the following imagery fragments. "
            "Each line is prefixed with its zero-based index.\n\n"
            f"Imagery fragments:\n{indexed_lines}"
        )

    def _parse_candidates(
        self, raw_response: str, fragment_count: int
    ) -> list[MotifCandidate]:
        payload = json.loads(raw_response)
        motifs_raw = payload.get("motifs")
        if not isinstance(motifs_raw, list):
            raise MotifInductionError(
                "LLM response did not include a motifs list"
            )

        candidates: list[MotifCandidate] = []
        for item in motifs_raw:
            if not isinstance(item, dict):
                raise MotifInductionError("Motif entries must be JSON objects")

            label = str(item.get("label", "")).strip()
            if not label:
                raise MotifInductionError("Motif label must be non-empty")

            rationale = str(item.get("rationale", "")).strip()
            if not rationale:
                raise MotifInductionError("Motif rationale must be non-empty")

            confidence = str(item.get("confidence", "")).strip().lower()
            if confidence not in _VALID_CONFIDENCE_LEVELS:
                raise MotifInductionError(
                    f"Invalid confidence level: {confidence!r}. "
                    f"Must be one of: {_VALID_CONFIDENCE_LEVELS}"
                )

            imagery_indices_raw = item.get("imagery_indices")
            if not isinstance(imagery_indices_raw, list):
                raise MotifInductionError("imagery_indices must be a list")

            imagery_indices: list[int] = []
            for idx in imagery_indices_raw:
                idx_int = int(idx)
                if idx_int < 0 or idx_int >= fragment_count:
                    raise MotifInductionError(
                        f"imagery_index {idx_int} is out of range "
                        f"(fragment_count={fragment_count})"
                    )
                imagery_indices.append(idx_int)

            candidates.append(
                MotifCandidate(
                    label=label,
                    rationale=rationale,
                    confidence=confidence,
                    imagery_indices=imagery_indices,
                )
            )

        return candidates
